### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by SunYM-hash** [hku-mars/M-detector#2]
你好，我看到cmake中注释掉了这个，然后编译会找不到python，是不是应该取消注释呢
```
# find_package(PythonLibs REQUIRED)
# find_path(MATPLOTLIB_CPP_INCLUDE_DIRS "matplotlibcpp.h")

```
![image](https://github.com/hku-mars/M-detector/assets/59947791/ed01c9c0-5853-451b-bc7e-45568407094b)

**Comment by zuowei1998** [comment]
+1
