### ISSUE TITLE
How about the performance of VLP-16?

### ISSUE THREAD

**Issue by qpc001** [hku-mars/M-detector#3]

**Comment by HuajieWu99** [comment]
Sorry currently we do not have the VLP 16 data.  Thus there is no parameter file provided for this LiDAR. Theoretically, M-detector can work well for different LiDARs. We recommend you to tune the parameters by yourselves for VLP-16 according to the tuning methods introduced in our Supplementary Information. This file can be downloaded via https://www.nature.com/articles/s41467-023-44554-8.
